import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { IpoCard } from "@/components/IpoCard";
import { AdSlot } from "@/components/AdSlot";
import { dataSource, formatSourceUpdate, ipos } from "@/data/ipos";

export default function HomePage() {
  const featured = ipos.slice(0, 4);
  const lead = featured[0];
  const totalLots = ipos.reduce((sum, ipo) => sum + ipo.lotCount, 0);
  return <><Header /><main>
    <section className="dataRibbon"><div className="container">Canlı veri kaynağı: {dataSource}. Son üretim: {formatSourceUpdate()}. Bilinmeyen alanlarda veri uydurulmaz.</div></section>
    <section className="hero"><div className="container heroGrid"><div className="heroCopy"><span className="heroBadge">Ücretsiz resmî veri + kaynaklı analiz</span><h1>Halka arzı sadece görme.<br /><em>Kaynağından anla.</em></h1><p>SPK bültenlerinden yeni halka arzları otomatik bulur, sermaye ve ortak satışı yapısını sadeleştirir; açıklanmayan bilgileri açıkça işaretler.</p><div className="heroActions"><Link className="primaryButton large" href="/halka-arzlar">Halka arzları incele</Link><Link className="secondaryButton large" href="/metodoloji">Nasıl çalışıyor?</Link></div><div className="trustRow"><span>✓ Resmî SPK kaynağı</span><span>✓ Yatırım tavsiyesi içermez</span><span>✓ Kaynaksız veri yayımlanmaz</span></div></div>
      {lead && <article className="heroPanel"><div className="heroPanelHeader"><div><span className="liveDot" /> Otomatik ön analiz</div><span>{lead.bulletinNo}</span></div><div className="heroCompany"><div className="companyLogo big">{lead.company.slice(0,2).toLocaleUpperCase("tr-TR")}</div><div><strong>{lead.company}</strong><span>{lead.ticker || "Borsa kodu bekleniyor"} · {lead.sector}</span></div><div className="heroScore"><strong>{lead.aiScore}</strong><span>/100</span></div></div><div className="signalGrid"><div><span>Sermaye artırımı</span><strong className="positive">{lead.capitalIncreaseShares.toLocaleString("tr-TR")}</strong></div><div><span>Ortak satışı</span><strong>{lead.shareholderSaleShares.toLocaleString("tr-TR")}</strong></div><div><span>Arz fiyatı</span><strong>₺{lead.price.toLocaleString("tr-TR")}</strong></div><div><span>Kapsam</span><strong className="warning">Ön analiz</strong></div></div><div className="heroInsight"><span>Otomatik özet</span><p>{lead.aiSummary}</p></div><div className="sourceChip">↗ {lead.sources.length} resmî kaynak</div></article>}
    </div></section>
    <section className="statsStrip"><div className="container statsGrid"><div><strong>{ipos.length}</strong><span>Gerçek SPK kaydı</span></div><div><strong>{totalLots.toLocaleString("tr-TR")}</strong><span>Toplam temel arz lotu</span></div><div><strong>{new Set(ipos.map((ipo) => ipo.bulletinNo)).size}</strong><span>İşlenen bülten</span></div><div><strong>0 ₺</strong><span>Ücretli veri API maliyeti</span></div></div></section>
    <section className="section"><div className="container"><div className="sectionHeading"><div><span className="eyebrow">Güncel görünüm</span><h2>SPK onayı alan son halka arzlar</h2><p>Rakamlar resmî bültenden alınır; talep tarihleri ve kod açıklanınca kayıt zenginleştirilir.</p></div><Link className="secondaryButton" href="/halka-arzlar">Tümünü gör</Link></div><div className="cardGrid">{featured.map((ipo) => <IpoCard ipo={ipo} key={ipo.id} />)}</div></div></section>
    <div className="container"><AdSlot slot={process.env.NEXT_PUBLIC_ADSENSE_HOME_SLOT} label="Ana sayfa reklam alanı" /></div>
    <section className="section mutedSection"><div className="container"><div className="sectionHeading centered"><div><span className="eyebrow">Şeffaf veri hattı</span><h2>Kaynak gelmeden yorum oluşmaz</h2><p>Otomasyon ücretsiz kaynaklarla çalışır ve her veri alanının kaynağını saklar.</p></div></div><div className="processGrid"><article><span>01</span><h3>SPK bülteni bulunur</h3><p>GitHub Actions günlük olarak resmî bülten sayfasını kontrol eder.</p></article><article><span>02</span><h3>PDF ayrıştırılır</h3><p>Şirket, fiyat, sermaye artırımı ve ortak satışı tablo üzerinden çıkarılır.</p></article><article><span>03</span><h3>Ücretsiz AI/fallback</h3><p>Cloudflare Workers AI varsa kaynak sınırlı özet üretir; yoksa şeffaf kural motoru çalışır.</p></article><article><span>04</span><h3>Site yeniden yayımlanır</h3><p>Değişiklik testlerden geçer ve Vercel uyumlu statik veri olarak sunulur.</p></article></div></div></section>
    <section className="finalCta"><div className="container finalCtaInner"><div><span className="eyebrow">Gerçek veri temeli</span><h2>Yalnız resmî kaynağa bağlı kayıtlar.</h2><p>Mevcut kayıtlar 2026 yılı boyunca yayımlanan ve halka arz onayı içeren resmî SPK bültenlerinden üretildi; günlük otomasyon yeni bültenleri tarar.</p></div><Link className="primaryButton large" href="/halka-arzlar">Kayıtları aç</Link></div></section>
  </main><Footer /></>;
}
